name: ci

on:
  push:
    branches:
      - 'master'

jobs:
  scrapyd_image:
    runs-on: ubuntu-latest
    steps:
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}
      -
        name: Build and push scrapyd server
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          file: scrapyd/Dockerfile
          push: true
          tags: deanrobertcook/quotes-scrapyd:latest